mapping_list <- c(
    "Argentina",
    "Bangladesh",
    "Brazil",
    "Central America",
    "Canada",
    "China",
    "Colombia",
    "Rest of E Asia",
    "Egypt",
    "Ethiopia",
    "EU",
    "Indonesia",
    "India",
    "Japan",
    "Korea",
    "Morroco",
    "Madagascar",
    "M East N Africa",
    "Mexico",
    "Malaysia",
    "Nigeria",
    "Oceania",
    "C Asia",
    "Other Europe",
    "Pakistan",
    "Phiilippines",
    "Poland",
    "Rest of S Asia",
    "Rest of SE Asia",
    "Russia",
    "S America",
    "SS Africa",
    "Turkey",
    "USA",
    "Vietnam",
    "Angola+DRC",
    "South Africa",
    "World"
)